version: '3.8'

services:
  app:
    build: .
    container_name: python-docker-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0