version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: always
